#!/usr/bin/env node
import {AuthUsers} from '../src/AuthUsers.js';
import {ToolCli} from '../src/ToolCli.js';

function printHelp() {
  console.log(`Usage: ./tools/userdel [--file PATH] USERNAME

Deletes a remote web client user from the ScanMeister users file.

Options:
  --file PATH   Users file path. Default: ${AuthUsers.DEFAULT_USERS_FILE}
`);
}

async function main() {
  const {options, positional} = ToolCli.parseCommonArguments(
    process.argv.slice(2),
    {defaultFile: AuthUsers.DEFAULT_USERS_FILE}
  );
  if (options.help) {
    printHelp();
    return;
  }

  const [username] = positional;
  if (!username || positional.length !== 1) {
    printHelp();
    process.exit(1);
  }

  const users = new AuthUsers(options.file);
  await users.remove(username);
  console.log(`Deleted user '${username}' from ${options.file}.`);
}

main().catch(ToolCli.fail);
